name: Build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: app
        run: west build -b stm32h747i_disco/stm32h747xx/m7

      - name: Run unit tests
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: host
        working-directory: app
        run: ../zephyr/scripts/twister -T tests -p native_sim --coverage --coverage-basedir .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
          gcov_include: 'app/lib/**'
          # disable_search: true
          # files: app/twister-out/coverage.json
          verbose: true
